import 'farm_details_menu.dart';

List<FarmHouse> farmHouse = [
  FarmHouse(
    id: 1,
    name: 'bhalala farm',
    image: 'assets/images/bhalala_farm.jpeg',
    subImage: [
      'assets/subImages/image1.jpg',
      'assets/subImages/image2.jpg',
      'assets/subImages/image3.jpg',
      'assets/subImages/image4.jpg',
      'assets/subImages/image5.jpg',
      'assets/subImages/image6.jpg',
    ],
    availability: Availability(
      kitchen: 1,
      bedroom: 2,
      bathroom: 3,
      khatla: 7,
      gadla: 8,
    ),
    farmHouseSize: 180,
    swimmingPoolSize: '15x12',
    totalCapacity: 25,
    extraPersonCharge: 500,
    contact: '9979599793',
    address: '309, Amazing Star, Nr Mahavir Circle, Yogi chowk, Surat',
    timeForEntry: TimeForEntry(
      hour12: '7:00 AM',
      hour24: '7:00 PM',
    ),
    timeForExit: TimeForExit(
      hour12: '12:00 AM',
      hour24: '12:00 AM',
    ),
    priceOtherDay: PriceOtherDay(
      day: 6500,
      night: 2500,
    ),
    priceWeekEnd: PriceWeekEnd(
      day: 13500,
      night: 0,
    ),
  ),
  FarmHouse(
    id: 2,
    name: 'Krishna Farm',
    image: 'assets/images/krishna_farm.jpeg',
    subImage: [
      'assets/subImages/krishna_farm1.jpeg',
      'assets/subImages/krishna_farm2.jpeg',
      'assets/subImages/krishna_farm3.jpeg',
      'assets/subImages/krishna_farm4.jpeg',
      'assets/subImages/krishna_farm5.jpeg',
      'assets/subImages/krishna_farm6.jpeg',
      'assets/subImages/krishna_farm7.jpeg',
      'assets/subImages/krishna_farm8.jpeg',
      'assets/subImages/krishna_farm9.jpeg',
    ],
    availability: Availability(
      kitchen: 1,
      bedroom: 2,
      bathroom: 2,
      khatla: 12,
      gadla: 15,
    ),
    farmHouseSize: 650,
    swimmingPoolSize: '12x20',
    totalCapacity: 15,
    extraPersonCharge: 500,
    contact: '9979599793',
    address: '309, Amazing Star, Nr Mahavir Circle, Yogi chowk, Surat',
    timeForEntry: TimeForEntry(
      hour12: '7:00 AM',
      hour24: '7:00 PM',
    ),
    timeForExit: TimeForExit(
      hour12: '12:00 AM',
      hour24: '12:00 AM',
    ),
    priceOtherDay: PriceOtherDay(
      day: 5500,
      night: 2500,
    ),
    priceWeekEnd: PriceWeekEnd(
      day: 12500,
      night: 0,
    ),
  ),
  FarmHouse(
    id: 3,
    name: 'Orange Villa',
    image: 'assets/images/orange_villa_farm.jpeg',
    subImage: [
      'assets/subImages/orange_villa_farm1.jpeg',
      'assets/subImages/orange_villa_farm2.jpeg',
      'assets/subImages/orange_villa_farm3.jpeg',
      'assets/subImages/orange_villa_farm4.jpeg',
      'assets/subImages/orange_villa_farm5.jpeg',
      'assets/subImages/orange_villa_farm6.jpeg',
      'assets/subImages/orange_villa_farm7.jpeg',
      'assets/subImages/orange_villa_farm8.jpeg',
      'assets/subImages/orange_villa_farm9.jpeg',
      'assets/subImages/orange_villa_farm10.jpeg',
      'assets/subImages/orange_villa_farm12.jpeg',
      'assets/subImages/orange_villa_farm11.jpeg',
    ],
    farmHouseSize: 800,
    swimmingPoolSize: '17x25',
    totalCapacity: 20,
    extraPersonCharge: 600,
    contact: '9979599793',
    address: '309, Amazing Star, Nr Mahavir Circle, Yogi chowk, Surat',
    timeForEntry: TimeForEntry(
      hour12: '7:00 AM',
      hour24: '7:00 PM',
    ),
    timeForExit: TimeForExit(
      hour12: '12:20 AM',
      hour24: '12:20 AM',
    ),
    priceOtherDay: PriceOtherDay(
      day: 9000,
      night: 3000,
    ),
    priceWeekEnd: PriceWeekEnd(
      day: 15500,
      night: 0,
    ),
  ),
];
